### PR TITLE
Responsiveness

### PR DESCRIPTION
**Pull request by adhvikmadhav**

### CODE REVIEW

**Comment by jdamerow** [comment]
the memorandum page is missing now. I think there was a misunderstanding. we want the html page but only the pdf for download.

**Comment by jdamerow** [comment]
yes, but the test should be there as well. the user should not have to download the pdf to read it. revert to its previous version and just remove the word doc download. that was the only thing that was wrong with it before.

**Comment by adhvikmadhav** [comment]
like this?
[image: image.png]

**Comment by jdamerow** [comment]
Not sure, I don’t see the image.  It how it was in your previous version.

**Pull request closed without merging**
