### PR TITLE
Story/web 30

### PR DESCRIPTION
**Pull request by ilobo22**
This is my initial thought process on how to format this section. I just need feedback on how you want to format it.

### CODE REVIEW

**Comment by jdamerow** [comment]
let's make the table take up the whole width of the page and not in a greyed out color and no table background color. Just plain text on plain background, and let's show everything from the diging organization.

**Comment by jdamerow** [comment]
- this doesn't seem to include all projects in the diging organization? The commits I see are not the most recent ones I believe.
- let's not use the all capitals font, but regular font and make the middle column left aligned not centered, and I would put the project as the first column.
image

**Comment by jdamerow** [comment]
and let's show the latest 10 commits

**Comment by jdamerow** [comment]
as discussed on slack, please use events endpoint

**Comment by jdamerow** [comment]
And I forgot, we also want a timestamp (day and time) for the events.

**Comment by ilobo22** [comment]
This plugin is only for retrieving the data. If somebody makes a commit, refreshing the page immediately won't retrieve the commit because there isn't any javascript.

**Comment by jdamerow** [comment]
issue not fixed

**Pull request closed without merging**
